networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: ubuntu/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - kafka-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  spark:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: spark
    ports:
      - "5000:5000"
    networks:
      - kafka-network

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - kafka-network



