version: '3.4'

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: ubuntu/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - kafka-network
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "twitter:1:1"
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  spark:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: spark
    depends_on:
      - kafka
    networks:
      - kafka-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - kafka-network



